/**
 * Image slots. Single source of truth for every image position on the site: name, fixed format, background type,
 * priority, page and a prompt core. `npm run assets:list` generates docs/ASSET-LIST.md from this file.
 * Files live in public/assets/ as <name>.avif|webp|jpg|png, optionally with width variants <name>-<width>.<ext>.
 * Until a file exists the slot shows its fallback. Atlas pictures use the dynamic name `atlas-<id>` (see slotDef).
 */
export interface SlotDef {
  w: number;
  h: number;
  /** "black": glowing motif on pure black, blended with `screen`; "scene": opaque image */
  bg: "black" | "scene";
  /** portrait variant used below 700 px viewport width */
  mobile?: string;
  /** 1 = needed first (hero), 6 = last */
  prio: number;
  page: string;
  /** English prompt core; the shared style anchor is added by docs/ASSET-LIST.md */
  prompt: string;
}

const d = (page: string, prio: number, bg: SlotDef["bg"], w: number, h: number, prompt: string, mobile?: string): SlotDef => ({ w, h, bg, mobile, prio, page, prompt });
const HOME = "Startseite";
const CULT = "Alte Kulturen";
const ENERGY = "Freie Energie";
const PLANTS = "Pflanzenatlas";
const PROFILE = "Pflanzenprofil";
const MINERALS = "Mineralatlas";
const ELEMENT = "Elementprofil Wasserstoff";
const KRISTALL = "Kristall-Atlas";
const KOERPER = "Der menschliche Körper";
const FREQ = "Frequenz-Seite";
const ATEM = "Atem-Seite";
const BESCH = "Beschwerden-Seite";
const CHAKREN = "Chakren-Seite";
const NAEHR = "Nährstoff-Seite";

export const SLOTS = {
  // ---- Startseite: hero (priority 1)
  "hero-world": d(HOME, 1, "scene", 3840, 2160, "wide cinematic night landscape, ancient temple city and dense jungle with a waterfall on the far left, pyramids and misty mountains on the far right, deep starry sky with planets, large calm dark area on the left 40 percent for text, empty space in the right center for a figure, no people", "hero-mobile"),
  "hero-figure": d(HOME, 1, "black", 2400, 3000, "profile of a serene woman with a crown of lush plants and flowers, beside a translucent glowing human body hologram with visible organs, neural pathways and a DNA helix, scientific hologram, on a pure black background"),
  "hero-planets": d(HOME, 1, "black", 2400, 1600, "four separate detailed planets and moons with atmosphere glow, different sizes, wide spacing, on a pure black background"),
  "hero-dna": d(HOME, 1, "black", 1200, 2400, "glowing double helix DNA strand, gold and cyan, vertical, elegant, on a pure black background"),
  "hero-lotus": d(HOME, 1, "black", 1600, 1600, "cluster of glowing luminous lotus and tropical flowers in pink and amber, on a pure black background"),
  "hero-bokeh": d(HOME, 1, "black", 3840, 2160, "floating golden dust particles and soft bokeh lights, sparse, dark, on a pure black background"),
  "hero-mobile": d(HOME, 1, "scene", 1080, 1920, "portrait version: same figure and world, figure in the upper half, dark calm area in the lower half for text"),

  // ---- Startseite: knowledge matrix tiles (priority 2), portrait tiles
  "tile-pflanzen": d(HOME, 2, "scene", 1000, 1200, "lush green medicinal plant with large leaves and small flowers, glowing, dark background"),
  "tile-baeume": d(HOME, 2, "scene", 1000, 1200, "ancient majestic tree with wide crown at dusk, golden light, dark background"),
  "tile-gemuese-obst": d(HOME, 2, "scene", 1000, 1200, "colourful arrangement of fresh fruit and vegetables, rich colours, dark background"),
  "tile-pilze": d(HOME, 2, "scene", 1000, 1200, "cluster of medicinal mushrooms on moss, soft glow, dark forest background"),
  "tile-mineralien": d(HOME, 2, "scene", 1000, 1200, "raw mineral crystals in blue and white with fine facets, glowing, dark background"),
  "tile-kristalle": d(HOME, 2, "scene", 1000, 1200, "large amethyst crystal cluster in violet, glowing, dark background"),
  "tile-koerper": d(HOME, 2, "scene", 1000, 1200, "translucent human torso with glowing organs, blue and orange, dark background"),
  "tile-naehrstoffe": d(HOME, 2, "scene", 1000, 1200, "glowing spheres in different colours representing vitamins and minerals, molecular look, dark background"),
  "tile-krankheiten": d(HOME, 2, "scene", 1000, 1200, "human silhouette with glowing red and blue signal lines, scientific, dark background"),
  "tile-atem": d(HOME, 2, "scene", 1000, 1200, "person meditating in lotus pose with soft light rays, dark background"),
  "tile-frequenzen": d(HOME, 2, "scene", 1000, 1200, "glowing concentric sound waves and geometric ripples in violet and blue, dark background"),
  "tile-geometrie": d(HOME, 2, "scene", 1000, 1200, "golden flower of life sacred geometry, glowing lines, dark background"),
  "tile-chakren": d(HOME, 2, "scene", 1000, 1200, "meditating figure with seven glowing colourful energy centres along the spine, dark background"),
  "tile-kulturen": d(HOME, 2, "scene", 1000, 1200, "ancient Egyptian pyramids and temple at golden hour, dramatic sky"),
  "tile-orte": d(HOME, 2, "scene", 1000, 1200, "ancient standing stones at dusk, dramatic sky, mystic atmosphere"),
  "tile-lab": d(HOME, 2, "scene", 1000, 1200, "dramatic collage of the earth's natural energy: a bright sun above a lightning storm, a waterfall and wind turbines, dark background"),

  // ---- Startseite: body atlas, plant atlas, sections (priority 3)
  "body-front": d(HOME, 3, "black", 2400, 3600, "translucent human body, front view, anatomical, glowing blue with organs visible in red and orange, on a pure black background"),
  "nutrient-ashwagandha": d(HOME, 3, "black", 800, 800, "ashwagandha root and green leaves, glowing, on a pure black background"),
  "nutrient-kurkuma": d(HOME, 3, "black", 800, 800, "fresh turmeric roots and powder, warm orange glow, on a pure black background"),
  "nutrient-ingwer": d(HOME, 3, "black", 800, 800, "fresh ginger root pieces, warm glow, on a pure black background"),
  "nutrient-knoblauch": d(HOME, 3, "black", 800, 800, "garlic bulbs and cloves, soft glow, on a pure black background"),
  "nutrient-gruener-tee": d(HOME, 3, "black", 800, 800, "green tea leaves, fresh and glowing, on a pure black background"),
  "nutrient-magnesium": d(HOME, 3, "black", 800, 800, "glowing blue molecule sphere with orbiting dots, on a pure black background"),
  "nutrient-omega3": d(HOME, 3, "black", 800, 800, "golden drops of oil with a nut, glowing, on a pure black background"),
  "nutrient-vitamin-d": d(HOME, 3, "black", 800, 800, "glowing sun symbol over a drop, warm gold, on a pure black background"),
  "condition-bg": d(HOME, 3, "scene", 1600, 900, "profile of a calm young woman with a glowing network of light around her head, dark background, space on the right"),
  "freq-orb": d(HOME, 3, "black", 1200, 1200, "glowing violet sacred geometry sphere with a meditating silhouette in front, on a pure black background"),
  "band-geometrie": d(HOME, 3, "scene", 1800, 600, "golden flower of life geometry glowing on a dark background, space on the left for text"),
  "band-kulturen": d(HOME, 3, "scene", 1800, 600, "ancient pyramids and temple ruins at golden hour, space on the left for text"),
  "band-orte": d(HOME, 3, "scene", 1800, 600, "sacred mountain site with ancient terraces in mist, space on the left for text"),
  "diy-extrakte": d(HOME, 3, "scene", 800, 1000, "glass bottles with plant extracts and herbs on a dark wooden table"),
  "diy-wasser": d(HOME, 3, "scene", 800, 1000, "glowing structured water in a glass with a swirling vortex, dark background"),
  "diy-raeuchern": d(HOME, 3, "scene", 800, 1000, "smoking incense bowl with herbs, atmospheric, dark background"),
  "diy-mikroskop": d(HOME, 3, "scene", 800, 1000, "antique microscope with warm light, dark background"),
  "library-bg": d(HOME, 3, "scene", 1800, 900, "old library with tall shelves and an open ancient book in warm light, space on the left for text"),
  "connected-earth": d(HOME, 3, "scene", 1800, 900, "Earth from space with a glowing network of connections across continents, dark space"),

  // ---- later pages (priority 4–6)
  "organ-heart": d("Körper", 4, "black", 1600, 1600, "one anatomical human heart, realistic but translucent and softly glowing, on a pure black background"),
  "organ-brain": d("Körper", 4, "black", 1600, 1600, "one anatomical human brain, realistic but translucent and softly glowing, on a pure black background"),
  "organ-lungs": d("Körper", 4, "black", 1600, 1600, "anatomical human lungs, translucent and softly glowing, on a pure black background"),
  "organ-liver": d("Körper", 4, "black", 1600, 1600, "anatomical human liver, translucent and softly glowing, on a pure black background"),
  "organ-stomach": d("Körper", 4, "black", 1600, 1600, "anatomical human stomach, translucent and softly glowing, on a pure black background"),
  "organ-intestines": d("Körper", 4, "black", 1600, 1600, "anatomical human intestines, translucent and softly glowing, on a pure black background"),
  "organ-kidneys": d("Körper", 4, "black", 1600, 1600, "anatomical human kidneys, translucent and softly glowing, on a pure black background"),
  "organ-skin": d("Körper", 4, "black", 1600, 1600, "cross-section of human skin layers, translucent and softly glowing, on a pure black background"),
  "organ-immune": d("Körper", 4, "black", 1600, 1600, "immune cells and lymph network, translucent and glowing, on a pure black background"),
  "organ-endocrine": d("Körper", 4, "black", 1600, 1600, "endocrine glands (pituitary, thyroid) as glowing anatomical illustration, on a pure black background"),
  "heart-botanical": d("Körper", 4, "black", 2000, 2400, "anatomical heart whose vessels grow into botanical plants and flowers, glowing, on a pure black background"),
  "globe-earth": d("Orte", 5, "black", 3000, 3000, "holographic Earth globe with glowing network lines connecting glowing points, on a pure black background"),
  "site-giza": d("Orte", 5, "scene", 1600, 1000, "Giza pyramids at dusk, dramatic light (better: own or freely licensed photo)"),
  "site-machu-picchu": d("Orte", 5, "scene", 1600, 1000, "Machu Picchu in morning mist (better: own or freely licensed photo)"),
  "site-angkor-wat": d("Orte", 5, "scene", 1600, 1000, "Angkor Wat at sunrise (better: own or freely licensed photo)"),
  "site-goebekli-tepe": d("Orte", 5, "scene", 1600, 1000, "Göbekli Tepe stone pillars (better: own or freely licensed photo)"),
  "site-malta-hypogeum": d("Orte", 5, "scene", 1600, 1000, "carved chamber of the Hypogeum of Malta, warm light"),
  "site-stonehenge": d("Orte", 5, "scene", 1600, 1000, "Stonehenge at dusk (better: own or freely licensed photo)"),
  "site-istanbul-mosque-dome": d("Orte", 5, "scene", 1600, 1000, "Ottoman mosque dome interior with golden light and geometric patterns, no people"),
  "diagram-dome-acoustics": d("Orte", 5, "black", 1600, 1600, "cross-section of a dome with sound waves, blueprint style, gold lines, on a pure black background"),
  "cymatics-1": d("Frequenz", 5, "black", 1600, 1600, "cymatic sand pattern, sacred geometry, glowing, on a pure black background"),
  "cymatics-2": d("Frequenz", 5, "black", 1600, 1600, "cymatic water pattern, concentric symmetry, glowing, on a pure black background"),
  "cymatics-3": d("Frequenz", 5, "black", 1600, 1600, "cymatic membrane pattern with fine nodal lines, glowing, on a pure black background"),
  "lab-waveform-bg": d("Frequenz", 5, "black", 3840, 1000, "wide glowing sine waves in cyan and gold, on a pure black background"),

  // ---- Alte Kulturen (priority 6): illustrations of places and objects; no readable text, no real living people
  "cult-hero": d(CULT, 6, "scene", 3200, 1500, "ancient world panorama at sunset, pyramids and a river valley in the distance, a carved stone wall at the right edge, a hooded wanderer seen from behind on the left, dark calm area on the left for text"),
  "cult-01": d(CULT, 6, "scene", 1800, 700, "Göbekli Tepe at golden hour, circle of large T-shaped limestone pillars with animal reliefs, wide landscape, no people"),
  "cult-02": d(CULT, 6, "scene", 1800, 700, "Stonehenge and a passage tomb at dusk with a low sun, early Neolithic landscape, no people"),
  "cult-03": d(CULT, 6, "scene", 1800, 700, "Giza pyramids and the Sphinx at sunset, warm desert light, no people"),
  "cult-04": d(CULT, 6, "scene", 1800, 700, "Mesopotamian ziggurat beside a river at dusk, mud-brick city, clay tablets in the foreground, no people"),
  "cult-05": d(CULT, 6, "scene", 1800, 700, "Indus Valley city of Mohenjo-daro, brick streets and the Great Bath at evening, no people"),
  "cult-06": d(CULT, 6, "scene", 1800, 700, "ancient Chinese landscape with a pagoda, terracotta warriors in rows and misty mountains, no real people"),
  "cult-07": d(CULT, 6, "scene", 1800, 700, "Maya step pyramid in the jungle at sunrise, stone relief of a calendar in the foreground, no people"),
  "cult-08": d(CULT, 6, "scene", 1800, 700, "Petra Treasury carved in rose-red rock with a Roman aqueduct and Inca stone walls blended into one dusk scene, no people"),
  "cult-theme-architektur": d(CULT, 6, "scene", 600, 600, "monumental ancient stone architecture, pyramids and temple columns, warm light"),
  "cult-theme-technologie": d(CULT, 6, "scene", 600, 600, "ancient bronze gear mechanism like the Antikythera device, close-up, warm light"),
  "cult-theme-spiritualitaet": d(CULT, 6, "scene", 600, 600, "ancient temple interior with candle light and carved reliefs, no people"),
  "cult-theme-astronomie": d(CULT, 6, "scene", 600, 600, "ancient stone observatory under a starry sky with a bright planet, no people"),
  "cult-theme-gesellschaft": d(CULT, 6, "scene", 600, 600, "ancient market city street from above at dusk, clay houses, no recognisable faces"),
  "cult-theme-artefakte": d(CULT, 6, "scene", 600, 600, "clay tablet with cuneiform and a carved stone seal on dark cloth, close-up"),
  "cult-theme-mythen": d(CULT, 6, "scene", 600, 600, "winged guardian relief of ancient Mesopotamia, glowing gold on dark stone"),
  "cult-theme-verborgenes": d(CULT, 6, "scene", 600, 600, "narrow ancient stone passage leading to a lit chamber, mysterious, no people"),

  // ---- Freie Energie der Erde (priority 7)
  "energy-hero": d(ENERGY, 7, "scene", 3200, 1400, "epic panorama of earth's natural energies: bright sun and aurora over mountains, a thunderstorm with lightning at the right, a waterfall and river on the left, wind turbines, a small volcano, dark calm area on the left for text, no people"),
  "energy-src-sonne": d(ENERGY, 7, "scene", 700, 540, "radiant sun over a landscape with solar panels at golden hour"),
  "energy-src-blitz": d(ENERGY, 7, "scene", 700, 540, "violet lightning storm over dark clouds"),
  "energy-src-wasser": d(ENERGY, 7, "scene", 700, 540, "powerful waterfall in a green valley"),
  "energy-src-meer": d(ENERGY, 7, "scene", 700, 540, "huge turquoise ocean wave curling, backlit"),
  "energy-src-wind": d(ENERGY, 7, "scene", 700, 540, "wind turbines on a hill in dramatic evening light"),
  "energy-src-geothermie": d(ENERGY, 7, "scene", 700, 540, "erupting volcano with glowing lava at dusk"),
  "energy-src-magnetfeld": d(ENERGY, 7, "scene", 700, 540, "earth from space with glowing blue magnetic field lines and aurora"),
  "energy-topic-atmosphaere": d(ENERGY, 7, "scene", 1200, 700, "earth atmosphere seen from the side with layered blue bands and a starry sky above, curved horizon"),
  "energy-topic-gewitter": d(ENERGY, 7, "scene", 1200, 700, "huge supercell thundercloud with branching lightning bolts over a plain"),
  "energy-topic-wasserkreislauf": d(ENERGY, 7, "scene", 1200, 700, "waterfall and river valley with clouds forming above, water cycle atmosphere"),
  "energy-topic-elektrokultur": d(ENERGY, 7, "scene", 1200, 700, "cross-section of garden soil with plant roots and a copper spiral coil, glowing fine lines"),
  "energy-topic-erdrotation": d(ENERGY, 7, "scene", 1200, 700, "planet earth with glowing blue magnetic field lines, seen from space"),
  "energy-topic-erdung": d(ENERGY, 7, "scene", 1200, 700, "bare feet standing on green grass and soil, soft morning light, close-up, subtle glowing lines in the ground"),
  "energy-topic-schmuck": d(ENERGY, 7, "scene", 1200, 700, "gold, silver and copper bracelets and gemstone rings on dark cloth, warm light, no hands"),
  "energy-topic-tesla": d(ENERGY, 7, "scene", 1200, 700, "tall early-1900s transmission tower with a large dome and blue electric discharge at dusk, no people"),
  // ---- Pflanzenatlas: landing page (priority 8). Existing tile/body/culture images are reused where they fit.
  "plants-hero": d(PLANTS, 8, "scene", 2800, 1300, "dark moody botanical still life: an open antique herbal book with pressed plant illustrations, a glass dropper bottle, a mortar, dried herbs, a stack of old leather books with gold lettering, lush green leaves and violet flowers framing the right side, warm candle light, calm dark area on the left for text, no people"),
  "plants-cat-kraeuter": d(PLANTS, 8, "scene", 1000, 1200, "fresh green medicinal herbs, rosemary sage and mint, painterly botanical, dark background"),
  "plants-cat-blueten": d(PLANTS, 8, "scene", 1000, 1200, "pink and violet fragrant flowers in bloom, soft glow, dark background"),
  "plants-cat-gewuerze": d(PLANTS, 8, "scene", 1000, 1200, "ginger root, turmeric and cinnamon sticks with whole spices, warm light, dark background"),
  "plants-cat-fruechte": d(PLANTS, 8, "scene", 1000, 1200, "a halved pomegranate with glowing seeds and other fruits, rich red, dark background"),
  "plants-cat-gemuese": d(PLANTS, 8, "scene", 1000, 1200, "fresh leafy green vegetables and bok choy, dew drops, dark background"),
  "plants-cat-algen": d(PLANTS, 8, "scene", 1000, 1200, "underwater seaweed and kelp with teal light rays, dark background"),
  "plants-map": d(PLANTS, 8, "scene", 2400, 1100, "old parchment world map in dark teal and sepia with illustrated plants on each continent, mountains and ocean, vintage cartography, calm and dark"),
  // ---- Pflanzenprofil: Ashwagandha ist die vollständige Vorlage (priority 8). Weitere Pflanzen bekommen später dieselben Namen `plant-<id>-…`.
  "plant-ashwagandha-hero": d(PROFILE, 8, "scene", 2800, 1100, "ashwagandha plant with green leaves, small white-yellow flowers, red berries inside papery husks and a thick pale-brown root system rising from dark soil, dark lush jungle background with soft golden light, subject on the right half, calm dark area on the left for text"),
  "plant-ashwagandha-sketch": d(PROFILE, 8, "scene", 700, 1000, "antique botanical pen-and-ink illustration of the whole ashwagandha plant with leaves, flower, berries and root on aged cream parchment, fine hatching, portrait, no text"),
  "plant-ashwagandha-parts": d(PROFILE, 8, "scene", 1600, 1000, "whole ashwagandha plant showing leaves, small flowers, red berries in husks and the complete root system in the soil, dark moody forest floor, plenty of empty dark space left and right for labels"),
  "plant-ashwagandha-photo": d(PROFILE, 8, "scene", 1200, 900, "macro close-up of an ashwagandha flower with pale yellow-white petals, green berries and leaves, soft natural light, shallow depth of field"),
  "plant-ashwagandha-thumb-wurzel": d(PROFILE, 8, "scene", 400, 500, "fresh ashwagandha taproot with fine side roots, soil-dusted, dark background"),
  "plant-ashwagandha-thumb-blatt": d(PROFILE, 8, "scene", 400, 500, "green ashwagandha leaves, slightly hairy, close-up, dark background"),
  "plant-ashwagandha-thumb-bluete": d(PROFILE, 8, "scene", 400, 500, "small pale yellow ashwagandha flower, close-up, dark background"),
  "plant-ashwagandha-thumb-frucht": d(PROFILE, 8, "scene", 400, 500, "ripe red ashwagandha berries in papery husks, close-up, dark background"),
  "plant-ashwagandha-stage-1": d(PROFILE, 8, "scene", 400, 500, "tiny ashwagandha seedling with two leaves in dark soil, dark background"),
  "plant-ashwagandha-stage-2": d(PROFILE, 8, "scene", 400, 500, "young leafy ashwagandha plant in growth, dark background"),
  "plant-ashwagandha-stage-3": d(PROFILE, 8, "scene", 400, 500, "ashwagandha plant in bloom with small pale flowers, dark background"),
  "plant-ashwagandha-stage-4": d(PROFILE, 8, "scene", 400, 500, "ashwagandha branch with ripe red berries in papery husks, dark background"),
  "plant-ashwagandha-stage-5": d(PROFILE, 8, "scene", 400, 500, "freshly harvested ashwagandha roots with soil, dark background"),
  "plant-ashwagandha-origin": d(PROFILE, 8, "scene", 800, 520, "ancient Indian temple ruins in a dry landscape, warm hazy light, illustration"),
  "plant-ashwagandha-powder": d(PROFILE, 8, "scene", 900, 700, "rustic wooden bowl of fine beige ashwagandha root powder with dried root pieces beside it, dark wood, warm light"),
  "compound-withaferin-a": d(PROFILE, 8, "scene", 900, 520, "hand-drawn chemical structural formula on aged parchment, steroid ring skeleton with a lactone ring, ink drawing; check the real structure of withaferin A before use (C28H38O6)"),
  "plant-ashwagandha-history-1": d(PROFILE, 8, "scene", 600, 450, "ancient Indian scholars and healers with palm-leaf manuscripts and herbs, sepia illustration"),
  "plant-ashwagandha-history-2": d(PROFILE, 8, "scene", 600, 450, "medieval herbalist at work with plants and manuscripts in Asia and Arabia, sepia illustration"),
  "plant-ashwagandha-history-3": d(PROFILE, 8, "scene", 600, 450, "18th and 19th century European naturalists studying plants, sepia engraving look"),
  "plant-ashwagandha-history-4": d(PROFILE, 8, "scene", 600, 450, "modern laboratory with plant extracts and glassware, warm light"),
  "plant-ashwagandha-combo-1": d(PROFILE, 8, "scene", 700, 420, "ashwagandha root next to fresh ginger root and a small jar of honey on dark wood"),
  "plant-ashwagandha-combo-2": d(PROFILE, 8, "scene", 700, 420, "ashwagandha root next to turmeric root and black peppercorns on dark wood"),
  "plant-ashwagandha-combo-3": d(PROFILE, 8, "scene", 700, 420, "ashwagandha root next to fresh rosemary sprigs and red berries on dark wood"),
  // shared pictures of the "Anwendungsformen" cards (all plant profiles)
  "form-tee": d(PROFILE, 8, "scene", 500, 600, "a steaming cup of herbal tea on a saucer with loose dried herbs, dark background"),
  "form-pulver": d(PROFILE, 8, "scene", 500, 600, "a mound of fine herbal root powder with dried root pieces, dark background"),
  "form-extrakt": d(PROFILE, 8, "scene", 500, 600, "amber glass jar of herbal extract with a label-free lid, dark background"),
  "form-kapseln": d(PROFILE, 8, "scene", 500, 600, "small amber glass bottle with a dropper next to a few plain capsules, dark background"),
  "form-tinktur": d(PROFILE, 8, "scene", 500, 600, "tall amber dropper bottle of herbal tincture with a few leaves, dark background"),
  "form-kochen": d(PROFILE, 8, "scene", 500, 600, "a small glass jar of ground herbal powder with a wooden spoon, kitchen look, dark background"),
  // ---- Pflanzenprofil: Granatapfel ist die vollständige Vorlage für Obst und Gemüse (priority 8)
  "plant-granatapfel-hero": d(PROFILE, 8, "scene", 2800, 1100, "ripe red pomegranates, one cut open showing glistening ruby arils, with glossy green leaves and a red blossom, dark moody orchard background with warm golden light, subject on the right half, calm dark area on the left for text"),
  "plant-granatapfel-sketch": d(PROFILE, 8, "scene", 700, 1000, "antique botanical pen-and-ink illustration of a pomegranate branch with leaves, flower, whole fruit and a cut fruit on aged cream parchment, fine hatching, portrait, no text"),
  "plant-granatapfel-parts": d(PROFILE, 8, "scene", 1600, 1000, "a pomegranate branch with glossy leaves and a red flower above, one whole fruit on the left and one fruit cut open on the right showing the arils, dark moody background, empty dark space left and right for labels"),
  "plant-granatapfel-origin": d(PROFILE, 8, "scene", 800, 520, "ancient Persian ruins with columns in a dry warm landscape, hazy golden light, illustration"),
  "plant-granatapfel-bowl": d(PROFILE, 8, "scene", 900, 700, "rustic wooden bowl full of glistening ruby pomegranate arils with a few leaves, dark wood, warm light"),
  "plant-granatapfel-stage-1": d(PROFILE, 8, "scene", 400, 500, "tiny pomegranate seedling with two leaves in dark soil, dark background"),
  "plant-granatapfel-stage-2": d(PROFILE, 8, "scene", 400, 500, "pomegranate branch with bright red flowers, dark background"),
  "plant-granatapfel-stage-3": d(PROFILE, 8, "scene", 400, 500, "small green unripe pomegranate fruit on a branch, dark background"),
  "plant-granatapfel-stage-4": d(PROFILE, 8, "scene", 400, 500, "ripe deep red pomegranate on a branch, dark background"),
  "compound-punicalagin": d(PROFILE, 8, "scene", 900, 520, "hand-drawn chemical structural formula on aged parchment, many connected aromatic phenol rings with hydroxyl groups, ink drawing; check the real structure of punicalagin (C48H28O30) before use"),
  "compound-ellagsaeure": d(PROFILE, 8, "scene", 400, 300, "close-up of ruby pomegranate arils with a soft glow, dark background"),
  "compound-anthocyane": d(PROFILE, 8, "scene", 400, 300, "deep red and violet berries with juice drops, dark background"),
  "compound-flavonoide": d(PROFILE, 8, "scene", 400, 300, "colourful fruit slices and leaves in soft light, dark background"),
  "compound-gerbstoffe": d(PROFILE, 8, "scene", 400, 300, "dried pomegranate peel pieces, brown and red, dark background"),
  "form-frisch": d(PROFILE, 8, "scene", 500, 600, "a small bowl of fresh ruby pomegranate arils, dark background"),
  "form-saft": d(PROFILE, 8, "scene", 500, 600, "a glass of freshly pressed red pomegranate juice with a halved fruit beside it, dark background"),
  "form-schale": d(PROFILE, 8, "scene", 500, 600, "dried pomegranate peel pieces and a cup of tea, dark background"),
  "form-samenoel": d(PROFILE, 8, "scene", 500, 600, "amber dropper bottle of pomegranate seed oil with a few seeds, dark background"),
  "plant-granatapfel-history-1": d(PROFILE, 8, "scene", 600, 450, "ancient Persian and Mesopotamian relief with a pomegranate motif, sepia illustration"),
  "plant-granatapfel-history-2": d(PROFILE, 8, "scene", 600, 450, "ancient Egyptian wall painting with pomegranates, sepia illustration"),
  "plant-granatapfel-history-3": d(PROFILE, 8, "scene", 600, 450, "ancient Greek vase scene with pomegranates and a goddess, sepia illustration"),
  "plant-granatapfel-history-4": d(PROFILE, 8, "scene", 600, 450, "medieval monastery garden with a monk tending fruit trees, sepia illustration"),
  "plant-granatapfel-history-5": d(PROFILE, 8, "scene", 600, 450, "modern laboratory with fruit extracts and glassware, warm light"),
  "plant-granatapfel-combo-1": d(PROFILE, 8, "scene", 700, 420, "pomegranate arils in a glass with honey and fresh ginger on dark wood"),
  "plant-granatapfel-combo-2": d(PROFILE, 8, "scene", 700, 420, "a halved pomegranate next to turmeric roots and powder on dark wood"),
  "plant-granatapfel-combo-3": d(PROFILE, 8, "scene", 700, 420, "pomegranate arils with fresh rosemary sprigs on dark wood"),
  "plant-granatapfel-combo-4": d(PROFILE, 8, "scene", 700, 420, "a rich dark stew with walnuts and pomegranate arils in a ceramic dish, persian style"),
  "plant-granatapfel-combo-5": d(PROFILE, 8, "scene", 700, 420, "a fresh green salad topped with ruby pomegranate arils, dark background"),
  // ---- Obst & Gemüse Atlas: landing page (priority 8). The tile image of the home page stands in until these exist.
  "obst-hero": d(PLANTS, 8, "scene", 2800, 1300, "a woven basket overflowing with colourful fruit and vegetables, pomegranate, pineapple, avocado, carrots and berries, in front of a misty green mountain valley with a lake, warm golden light, calm dark area on the left for text, no people"),
  "obst-sketch": d(PLANTS, 8, "scene", 700, 1000, "antique botanical pen-and-ink illustration of a pomegranate branch with fruit and leaves on aged cream parchment, fine hatching, portrait, no text"),
  "obst-cat-obst": d(PLANTS, 8, "scene", 1000, 800, "a colourful heap of sweet fruit, apples, pears and grapes, rich colours, dark background"),
  "obst-cat-beeren": d(PLANTS, 8, "scene", 1000, 800, "blueberries, raspberries and blackberries with dew, rich colours, dark background"),
  "obst-cat-zitrus": d(PLANTS, 8, "scene", 1000, 800, "halved oranges, lemons and limes, bright and juicy, dark background"),
  "obst-cat-kernobst": d(PLANTS, 8, "scene", 1000, 800, "red and green apples and pears, fresh with leaves, dark background"),
  "obst-cat-steinobst": d(PLANTS, 8, "scene", 1000, 800, "peaches, cherries and plums, ripe and glossy, dark background"),
  "obst-cat-tropen": d(PLANTS, 8, "scene", 1000, 800, "pineapple, papaya, dragon fruit and mango, tropical colours, dark background"),
  "obst-cat-gemuese": d(PLANTS, 8, "scene", 1000, 800, "a rustic crate of classic fresh vegetables, dark background"),
  "obst-cat-blatt": d(PLANTS, 8, "scene", 1000, 800, "fresh leafy greens, spinach and lettuce with water drops, dark background"),
  "obst-cat-wurzel": d(PLANTS, 8, "scene", 1000, 800, "carrots, beetroot and root vegetables with soil, dark background"),
  "obst-cat-huelsen": d(PLANTS, 8, "scene", 1000, 800, "bowls of lentils, beans and peas in many colours, dark background"),
  "obst-cat-kohl": d(PLANTS, 8, "scene", 1000, 800, "a green cabbage, broccoli and cauliflower, fresh, dark background"),
  "obst-cat-nachtschatten": d(PLANTS, 8, "scene", 1000, 800, "red tomatoes, peppers and a purple aubergine, dark background"),
  "obst-cat-kuerbis": d(PLANTS, 8, "scene", 1000, 800, "orange pumpkins, cucumbers and courgettes, dark background"),
  "obst-cat-zwiebel": d(PLANTS, 8, "scene", 1000, 800, "garlic bulbs, onions and leeks, dark background"),
  "obst-cat-nuesse": d(PLANTS, 8, "scene", 1000, 800, "a mixture of nuts and seeds in a rustic bowl, dark background"),
  "obst-cat-sprossen": d(PLANTS, 8, "scene", 1000, 800, "fresh bean and alfalfa sprouts in a small glass dish, dark background"),
  "obst-map": d(PLANTS, 8, "scene", 2400, 1100, "old parchment world map in dark teal and sepia with illustrated fruit and vegetables on each continent, a pineapple, oranges, corn and rice, vintage cartography, calm and dark"),
  "obst-kueche-mittelmeer": d(PLANTS, 8, "scene", 800, 600, "a sunny Mediterranean market with olives, tomatoes and aubergines, illustration"),
  "obst-kueche-asien": d(PLANTS, 8, "scene", 800, 600, "an Asian market with ginger, pak choi and rice paddies in the background, illustration"),
  "obst-kueche-suedamerika": d(PLANTS, 8, "scene", 800, 600, "a South American market with corn, chilli and quinoa in colourful baskets, illustration"),
  "obst-kueche-afrika": d(PLANTS, 8, "scene", 800, 600, "an African market with millet, okra and cassava, warm light, illustration"),
  "obst-kueche-orient": d(PLANTS, 8, "scene", 800, 600, "an oriental bazaar with pomegranates, dates and chickpeas, warm lamp light, illustration"),
  "obst-rezept-smoothies": d(PLANTS, 8, "scene", 600, 600, "two colourful fruit smoothies in glasses with fresh fruit around them, dark background"),
  "obst-rezept-salate": d(PLANTS, 8, "scene", 600, 600, "a fresh colourful salad bowl with leaves, tomatoes and pomegranate seeds, dark background"),
  "obst-rezept-warm": d(PLANTS, 8, "scene", 600, 600, "a warm vegetable stew in a ceramic pot with herbs, steam rising, dark background"),
  // ---- Baum Atlas: landing page (priority 8). The tile image `tile-baeume` stands in for the hero until these exist.
  "baum-hero": d(PLANTS, 8, "scene", 2800, 1300, "a gigantic ancient world tree with glowing golden roots spreading through the earth and a luminous crown, a mountain valley with a waterfall and a lake behind, magical warm light and floating light particles, calm darker area on the left for text, no people"),
  "baum-system": d(PLANTS, 8, "scene", 1600, 1040, "a large tree seen in cross-section: sunlight and glowing green energy flowing through crown, trunk and roots, mycorrhizal fungal threads in the soil connecting to a second tree, mushrooms at the ground, night sky with stars, empty space at the left and right edges for labels"),
  "baum-torus": d(PLANTS, 8, "scene", 1200, 760, "a luminous tree inside a glowing torus-shaped field of fine blue and golden lines, symbolic energy diagram on a dark background, elegant, no text"),
  "baum-map": d(PLANTS, 8, "scene", 2400, 1100, "a dark stylised world map in teal and gold with glowing green forest areas on every continent and fine connecting lines, calm and dark"),
  "baum-cat-laub": d(PLANTS, 8, "scene", 800, 960, "a mighty broadleaf oak tree in summer under a blue sky, dark background"),
  "baum-cat-nadel": d(PLANTS, 8, "scene", 800, 960, "tall dark conifer trees in a misty forest, dark background"),
  "baum-cat-obst": d(PLANTS, 8, "scene", 800, 960, "an apple tree full of ripe red apples, dark background"),
  "baum-cat-blueten": d(PLANTS, 8, "scene", 800, 960, "a blossoming cherry tree with pink flowers, dark background"),
  "baum-cat-tropen": d(PLANTS, 8, "scene", 800, 960, "a lush tropical rainforest tree with hanging lianas, dark background"),
  "baum-cat-heil": d(PLANTS, 8, "scene", 800, 960, "an ancient healing tree with a spiral trunk in warm light, dark background"),
  "baum-cat-berg": d(PLANTS, 8, "scene", 800, 960, "a lone pine tree on a mountain ridge with snowy peaks, dark background"),
  "baum-cat-trocken": d(PLANTS, 8, "scene", 800, 960, "an acacia tree in a golden dry savanna at sunset, dark background"),
  "baum-cat-holz": d(PLANTS, 8, "scene", 800, 960, "giant redwood trunks in a forest with light rays, dark background"),
  "baum-ebene-wissenschaft": d(PLANTS, 8, "scene", 600, 800, "a green leaf with glowing veins and tiny scientific symbols, microscope look, dark background"),
  "baum-ebene-traditionell": d(PLANTS, 8, "scene", 600, 800, "an old oak with a medicine woman gathering bark and herbs, painterly, warm light"),
  "baum-ebene-geometrisch": d(PLANTS, 8, "scene", 600, 800, "a golden spiral and fractal branching pattern, glowing lines on a dark background"),
  "baum-ebene-spirituell": d(PLANTS, 8, "scene", 600, 800, "a meditating figure under a glowing world tree, mystical light, dark background"),
  "baum-old-methusalem": d(PLANTS, 8, "scene", 600, 800, "an ancient gnarled bristlecone pine on a rocky mountain slope, dramatic light"),
  "baum-old-olive": d(PLANTS, 8, "scene", 600, 800, "a huge ancient olive tree with a hollow twisted trunk in a Mediterranean grove"),
  "baum-old-jomon": d(PLANTS, 8, "scene", 600, 800, "a massive ancient Japanese cedar in a misty moss-covered forest"),
  "baum-old-baobab": d(PLANTS, 8, "scene", 600, 800, "a baobab tree with a thick trunk in a savanna at sunset"),
  "baum-old-eiche": d(PLANTS, 8, "scene", 600, 800, "a very old mighty oak with a wide crown and thick branches in an English meadow"),
  "baum-oeko": d(PLANTS, 8, "scene", 1600, 800, "the base of a huge old tree with a deer, birds, mushrooms, insects and moss around it, forest ecosystem, soft magical light, empty space on the right for text"),
  "baum-holz": d(PLANTS, 8, "scene", 800, 450, "a stack of cut logs and timber boards in warm light, dark background"),
  "baum-kultur": d(PLANTS, 8, "scene", 800, 450, "stone temples and statues among ancient trees, a figure meditating, mystical light"),
  "baum-forschung": d(PLANTS, 8, "scene", 800, 450, "a green seedling growing in front of a research laboratory with glassware, warm light"),

  // ---- Mineralatlas (priority 8)
  "mineral-hero": d(MINERALS, 8, "scene", 2800, 1300, "the Earth as a glowing planet in the centre right surrounded by floating raw crystals and mineral rocks in purple, gold, blue and white, a mountain waterfall landscape at the lower right, a dark calm area on the left for text, soft golden light and sparkles, no text, no letters, no symbols"),
  "element-h": d(MINERALS, 8, "scene", 600, 720, "a clear crystal with a tiny bubble of hydrogen gas, icy blue glow, centred on a dark background, glowing, no text"),
  "element-c": d(MINERALS, 8, "scene", 600, 720, "a diamond and a lump of graphite side by side, white and black, centred on a dark background, glowing, no text"),
  "element-o": d(MINERALS, 8, "scene", 600, 720, "a deep blue faceted crystal with an oxygen bubble glow, centred on a dark background, glowing, no text"),
  "element-na": d(MINERALS, 8, "scene", 600, 720, "white cubic rock salt crystals, centred on a dark background, glowing, no text"),
  "element-mg": d(MINERALS, 8, "scene", 600, 720, "green faceted magnesium-rich crystals such as olivine, centred on a dark background, glowing, no text"),
  "element-si": d(MINERALS, 8, "scene", 600, 720, "clear and smoky quartz crystals, centred on a dark background, glowing, no text"),
  "element-ca": d(MINERALS, 8, "scene", 600, 720, "white and pale blue calcite crystals, centred on a dark background, glowing, no text"),
  "element-fe": d(MINERALS, 8, "scene", 600, 720, "rusty red iron ore with metallic hematite shine, centred on a dark background, glowing, no text"),
  "element-cu": d(MINERALS, 8, "scene", 600, 720, "a lump of native copper with green and orange tones, centred on a dark background, glowing, no text"),
  "element-zn": d(MINERALS, 8, "scene", 600, 720, "grey-blue zinc ore crystals, sphalerite, centred on a dark background, glowing, no text"),
  "element-ag": d(MINERALS, 8, "scene", 600, 720, "a branching lump of native silver, bright white metallic, centred on a dark background, glowing, no text"),
  "element-au": d(MINERALS, 8, "scene", 600, 720, "a raw gold nugget, warm golden glow, centred on a dark background, glowing, no text"),
  "element-i": d(MINERALS, 8, "scene", 600, 720, "dark violet iodine crystals with a purple vapour glow, centred on a dark background, glowing, no text"),
  "mineral-reise-atom": d(MINERALS, 8, "black", 600, 600, "a glowing atom with orbiting electrons, glowing, on a pure black background, no text"),
  "mineral-reise-molekuel": d(MINERALS, 8, "black", 600, 600, "a ball-and-stick molecule of silicon and oxygen, glowing, on a pure black background, no text"),
  "mineral-reise-gitter": d(MINERALS, 8, "black", 600, 600, "a regular crystal lattice of connected spheres, glowing, on a pure black background, no text"),
  "mineral-reise-kristall": d(MINERALS, 8, "black", 600, 600, "a single violet crystal point, glowing, on a pure black background, no text"),
  "mineral-reise-mineral": d(MINERALS, 8, "black", 600, 600, "a polished raw mineral specimen, glowing, on a pure black background, no text"),
  "mineral-reise-gestein": d(MINERALS, 8, "black", 600, 600, "a rough dark rock with mineral veins, glowing, on a pure black background, no text"),
  "mineral-reise-gebirge": d(MINERALS, 8, "black", 600, 600, "a snowy mountain range, glowing, on a pure black background, no text"),
  "mineral-reise-planet": d(MINERALS, 8, "black", 600, 600, "the Earth seen from space, glowing, on a pure black background, no text"),
  "mineral-quarz-1": d(MINERALS, 8, "black", 1600, 1300, "a large cluster of clear quartz crystals on dark rock, glowing, on a pure black background"),
  "mineral-quarz-2": d(MINERALS, 8, "black", 1600, 1300, "a single tall clear quartz point crystal with sharp facets, on a pure black background"),
  "mineral-quarz-3": d(MINERALS, 8, "black", 1600, 1300, "a quartz crystal with a fine rainbow inside, side view, on a pure black background"),
  "mineral-quarz-4": d(MINERALS, 8, "black", 1600, 1300, "small quartz crystals growing in a geode, on a pure black background"),
  "mineral-bild-magma": d(MINERALS, 8, "scene", 800, 600, "a glowing lava flow and a volcano at dusk, cinematic, no people"),
  "mineral-bild-meta": d(MINERALS, 8, "scene", 800, 600, "folded banded gneiss rock in a mountain cliff, cinematic, no people"),
  "mineral-bild-sedi": d(MINERALS, 8, "scene", 800, 600, "layered sandstone cliffs in warm desert light, cinematic, no people"),
  "mineral-bild-hydro": d(MINERALS, 8, "scene", 800, 600, "a cave wall with blue glowing crystal veins and clusters, cinematic, no people"),
  "mineral-map": d(MINERALS, 8, "scene", 2400, 1100, "a dark stylised world map in deep blue and gold with fine glowing contour lines, calm and dark, no text"),
  "mineral-ort-brasilien": d(MINERALS, 8, "scene", 600, 400, "amethyst and quartz geodes in a Brazilian mine landscape, dramatic light, no people"),
  "mineral-ort-madagaskar": d(MINERALS, 8, "scene", 600, 400, "large crystal formations in red earth, Madagascar, dramatic light, no people"),
  "mineral-ort-schweiz": d(MINERALS, 8, "scene", 600, 400, "alpine rock face with a crystal cleft in the Swiss Alps, dramatic light, no people"),
  "mineral-ort-usa": d(MINERALS, 8, "scene", 600, 400, "small double-terminated clear quartz crystals in dark rock, New York, dramatic light, no people"),
  "mineral-ort-uruguay": d(MINERALS, 8, "scene", 600, 400, "a large amethyst geode cut open, warm light, dramatic light, no people"),
  "mineral-ort-sambia": d(MINERALS, 8, "scene", 600, 400, "deep violet amethyst crystals in a rocky landscape, dramatic light, no people"),
  "mineral-ort-indien": d(MINERALS, 8, "scene", 600, 400, "pink rose quartz masses in a rocky hillside, dramatic light, no people"),
  "mineral-ort-schottland": d(MINERALS, 8, "scene", 600, 400, "smoky quartz crystals in granite in the Scottish highlands, dramatic light, no people"),
  "mineral-ort-deutschland": d(MINERALS, 8, "scene", 600, 400, "polished banded agate slices in a workshop, warm light, dramatic light, no people"),
  "mineral-ort-spanien": d(MINERALS, 8, "scene", 600, 400, "golden citrine crystals in a rocky terrain, dramatic light, no people"),
  "mineral-anw-schmuck": d(MINERALS, 8, "scene", 600, 600, "a faceted gemstone ring on dark velvet, dark background, no text"),
  "mineral-anw-technik": d(MINERALS, 8, "scene", 600, 600, "a mechanical wristwatch movement with a small quartz oscillator, dark background, no text"),
  "mineral-anw-optik": d(MINERALS, 8, "scene", 600, 600, "glass lenses and a laser beam in a laboratory, dark background, no text"),
  "mineral-anw-bau": d(MINERALS, 8, "scene", 600, 600, "an ancient stone temple wall of granite blocks, dark background, no text"),
  "mineral-anw-heil": d(MINERALS, 8, "scene", 600, 600, "a gathering of violet and pink crystals on a cloth, soft candle light, dark background, no text"),
  "mineral-anw-forschung": d(MINERALS, 8, "scene", 600, 600, "a crystal under a polarising microscope with colourful patterns, dark background, no text"),
  "mineral-anw-elektronik": d(MINERALS, 8, "scene", 600, 600, "a circuit board with a small metal crystal oscillator, dark background, no text"),
  "mineral-anw-alltag": d(MINERALS, 8, "scene", 600, 600, "glass bottles and a flint stone tool on a wooden table, dark background, no text"),
  "mineral-hist-stein": d(MINERALS, 8, "scene", 600, 500, "stone age flint blades and tools on rock, painterly, warm light, no text"),
  "mineral-hist-aegypten": d(MINERALS, 8, "scene", 600, 500, "an ancient Egyptian amulet and jewellery with amethyst beads, painterly, warm light, no text"),
  "mineral-hist-antike": d(MINERALS, 8, "scene", 600, 500, "a Greek marble statue holding a crystal sphere, painterly, warm light, no text"),
  "mineral-hist-mittelalter": d(MINERALS, 8, "scene", 600, 500, "a medieval scholar studying gemstones in a candle-lit study, painterly, warm light, no text"),
  "mineral-hist-moderne": d(MINERALS, 8, "scene", 600, 500, "a modern laboratory with crystals and measuring instruments, painterly, warm light, no text"),

  // ---- Elementprofil Wasserstoff (priority 8)
  "element-h-hero": d(ELEMENT, 8, "scene", 2800, 1300, "a large transparent glass sphere containing a glowing blue atom nucleus with thin orbit rings, floating over dark rocks and a waterfall in a night landscape, small soap-bubble spheres around it, a dark calm area on the left for text, no text, no letters"),
  "element-h-universum": d(ELEMENT, 8, "scene", 800, 600, "a spiral galaxy and nebula with glowing hydrogen clouds in blue and violet, deep space, no text"),
  "element-h-erde-1": d(ELEMENT, 8, "scene", 600, 400, "a glacier and blue ocean seen from above, clear cold light, no people"),
  "element-h-erde-2": d(ELEMENT, 8, "scene", 600, 400, "a steaming geyser and volcanic hot spring in a rocky landscape, no people"),
  "element-h-verb-wasser": d(ELEMENT, 8, "scene", 600, 600, "a water molecule as a ball-and-stick model with one red oxygen and two white hydrogen atoms, glowing, dark background, no text"),
  "element-h-verb-methan": d(ELEMENT, 8, "scene", 600, 600, "a methane molecule as a ball-and-stick model, one grey carbon and four white hydrogen atoms, dark background, no text"),
  "element-h-verb-ammoniak": d(ELEMENT, 8, "scene", 600, 600, "an ammonia molecule as a ball-and-stick model, one blue nitrogen and three white hydrogen atoms, dark background, no text"),
  "element-h-verb-salzsaeure": d(ELEMENT, 8, "scene", 600, 600, "a hydrogen chloride molecule as a ball-and-stick model, one green chlorine and one white hydrogen atom, dark background, no text"),
  "element-h-anw-energie": d(ELEMENT, 8, "scene", 600, 450, "a futuristic city powered by a hydrogen fuel cell, blue glowing energy, cinematic, no text"),
  "element-h-anw-raumfahrt": d(ELEMENT, 8, "scene", 600, 450, "a rocket launching at dawn with a bright exhaust flame, cinematic, no text"),
  "element-h-anw-industrie": d(ELEMENT, 8, "scene", 600, 450, "a chemical plant with tall columns and pipes at dusk, cinematic, no text"),
  "element-h-anw-metall": d(ELEMENT, 8, "scene", 600, 450, "glowing molten metal being poured in a steel mill, cinematic, no text"),
  "element-h-anw-mobil": d(ELEMENT, 8, "scene", 600, 450, "a modern hydrogen fuel cell car on a road at dusk, cinematic, no text"),
  "element-h-anw-zukunft": d(ELEMENT, 8, "scene", 600, 450, "a green hydrogen plant with wind turbines and solar panels at sunrise, cinematic, no text"),
  "element-h-hist-urzeit": d(ELEMENT, 8, "scene", 600, 450, "an early human around a campfire in a cave, firelight, painterly, no text"),
  "element-h-hist-alchemie": d(ELEMENT, 8, "scene", 600, 450, "an alchemist's workshop with flasks and a burning flame, painterly, painterly, no text"),
  "element-h-hist-wissenschaft": d(ELEMENT, 8, "scene", 600, 450, "an 18th century laboratory with glass apparatus and a scientist, warm light, painterly, no text"),
  "element-h-hist-raumfahrt": d(ELEMENT, 8, "scene", 600, 450, "a rocket on a launch pad with steam, vintage space age, painterly, no text"),
  "element-h-hist-zukunft": d(ELEMENT, 8, "scene", 600, 450, "a clean future landscape with wind turbines and a glowing hydrogen tank, painterly, no text"),

  // ---- Kristall-Atlas (priority 8)
  "kristall-hero": d(KRISTALL, 8, "scene", 2800, 1300, "a huge glowing violet amethyst crystal cluster in the centre right inside a dark cave, a golden sacred geometry circle behind it, a view out to a mountain lake at sunset on the right, small floating crystals, a dark calm area on the left for text, no text, no letters"),
  "kristall-cat-alle": d(KRISTALL, 8, "scene", 600, 672, "a mixed cluster of amethyst, quartz and rose quartz crystals, glowing, dark background, no text"),
  "kristall-cat-quarz": d(KRISTALL, 8, "scene", 600, 672, "a cluster of clear and smoky quartz crystals, dark background, no text"),
  "kristall-cat-edel": d(KRISTALL, 8, "scene", 600, 672, "faceted gemstones in purple, blue and red, sparkling, dark background, no text"),
  "kristall-cat-heil": d(KRISTALL, 8, "scene", 600, 672, "green and violet healing stones in a bowl, soft light, dark background, no text"),
  "kristall-cat-roh": d(KRISTALL, 8, "scene", 600, 672, "raw rough pink and white crystal points on dark rock, dark background, no text"),
  "kristall-cat-trommel": d(KRISTALL, 8, "scene", 600, 672, "polished tumbled stones in warm colours, dark background, no text"),
  "kristall-cat-selten": d(KRISTALL, 8, "scene", 600, 672, "a rare rainbow crystal with fine inclusions, glowing, dark background, no text"),
  "kristall-cat-meteor": d(KRISTALL, 8, "scene", 600, 672, "a dark meteorite fragment with crystal patterns, dark background, no text"),
  "kristall-cat-farbe": d(KRISTALL, 8, "scene", 600, 672, "bright blue and violet colour crystals, glowing, dark background, no text"),
  "kristall-cat-sammler": d(KRISTALL, 8, "scene", 600, 672, "a museum quality mineral specimen on a stand, red crystals, dark background, no text"),
  "kristall-system": d(KRISTALL, 8, "black", 900, 1200, "a large glowing violet crystal prism with a fine network of glowing lines inside, on a pure black background"),
  "kristall-amethyst-1": d(KRISTALL, 8, "black", 1600, 1300, "a large cluster of violet amethyst crystals on dark rock, glowing, on a pure black background"),
  "kristall-amethyst-2": d(KRISTALL, 8, "black", 1600, 1300, "a single tall amethyst crystal point with sharp facets, on a pure black background"),
  "kristall-amethyst-3": d(KRISTALL, 8, "black", 1600, 1300, "an amethyst geode cut open showing crystals, on a pure black background"),
  "kristall-amethyst-4": d(KRISTALL, 8, "black", 1600, 1300, "small amethyst crystals growing in a cluster, on a pure black background"),
  "kristall-anw-meditation": d(KRISTALL, 8, "scene", 600, 630, "a person meditating with a crystal in the hand, candle light, dark background, no text"),
  "kristall-anw-wohnraum": d(KRISTALL, 8, "scene", 600, 630, "a calm living room with crystal decoration on a shelf, dark background, no text"),
  "kristall-anw-schmuck": d(KRISTALL, 8, "scene", 600, 630, "a gemstone ring and necklace on dark velvet, dark background, no text"),
  "kristall-anw-heil": d(KRISTALL, 8, "scene", 600, 630, "crystals laid out on a cloth for a relaxation session, soft light, dark background, no text"),
  "kristall-anw-wasser": d(KRISTALL, 8, "scene", 600, 630, "a glass of water with a crystal beside it, dark background, no text"),
  "kristall-anw-garten": d(KRISTALL, 8, "scene", 600, 630, "crystals among plants and stones in a garden, dark background, no text"),
  "kristall-anw-sammlung": d(KRISTALL, 8, "scene", 600, 630, "a display case with mineral specimens in a museum, dark background, no text"),
  "kristall-anw-deko": d(KRISTALL, 8, "scene", 600, 630, "a decorative geode and crystal sculpture in a room, dark background, no text"),
  "kristall-map": d(KRISTALL, 8, "scene", 2400, 1200, "a dark stylised world map in violet and gold with fine glowing contour lines, calm and dark, no text"),
  "kristall-hist-aegypten": d(KRISTALL, 8, "scene", 600, 500, "an ancient Egyptian amulet and jewellery with lapis lazuli and amethyst, painterly, warm light, no text"),
  "kristall-hist-antike": d(KRISTALL, 8, "scene", 600, 500, "a Greek marble statue holding a crystal sphere, painterly, warm light, no text"),
  "kristall-hist-mittelalter": d(KRISTALL, 8, "scene", 600, 500, "a medieval scholar studying gemstones in a candle-lit study, painterly, warm light, no text"),
  "kristall-hist-moderne": d(KRISTALL, 8, "scene", 600, 500, "a modern laboratory with crystals and measuring instruments, painterly, warm light, no text"),
  "kristall-thema-mineralien": d(KRISTALL, 8, "scene", 600, 520, "raw mineral rocks in blue and white, glowing, dark background, no text"),
  "kristall-thema-elemente": d(KRISTALL, 8, "scene", 600, 520, "a periodic table cell glowing with a crystal, dark background, no text"),
  "kristall-thema-geologie": d(KRISTALL, 8, "scene", 600, 520, "layered rock strata and a volcano, dark background, no text"),
  "kristall-thema-frequenzen": d(KRISTALL, 8, "scene", 600, 520, "a glowing sound wave pattern in sand, cymatics, dark background, no text"),
  "kristall-thema-kulturen": d(KRISTALL, 8, "scene", 600, 520, "ancient stone temples and statues, dark background, no text"),
  "kristall-thema-forschung": d(KRISTALL, 8, "scene", 600, 520, "a microscope and crystal lattice diagram, dark background, no text"),
  "koerper-hero": d(KOERPER, 8, "scene", 2800, 1300, "a glowing translucent human body in the centre right, front view, with a faintly visible skeleton, muscles, nerves and organs in blue, gold and red, a soft golden halo behind it, small floating particles, a dark calm area on the left for text, no text, no letters"),
  "koerper-sys-nerven": d(KOERPER, 8, "scene", 500, 560, "a glowing network of nerves and a brain in violet, dark background, no text"),
  "koerper-sys-hormon": d(KOERPER, 8, "scene", 500, 560, "glowing endocrine glands, thyroid and pituitary, in orange, dark background, no text"),
  "koerper-sys-kreislauf": d(KOERPER, 8, "scene", 500, 560, "a glowing heart with arteries and veins in red and blue, dark background, no text"),
  "koerper-sys-atmung": d(KOERPER, 8, "scene", 500, 560, "glowing lungs and bronchial tree in pink and violet, dark background, no text"),
  "koerper-sys-verdauung": d(KOERPER, 8, "scene", 500, 560, "glowing stomach and intestines in warm orange, dark background, no text"),
  "koerper-sys-muskel": d(KOERPER, 8, "scene", 500, 560, "glowing muscle fibres of an arm in deep red, dark background, no text"),
  "koerper-sys-skelett": d(KOERPER, 8, "scene", 500, 560, "a glowing skeleton in ivory and blue, dark background, no text"),
  "koerper-sys-immun": d(KOERPER, 8, "scene", 500, 560, "glowing white blood cells and a shield motif in violet, dark background, no text"),
  "koerper-sys-harn": d(KOERPER, 8, "scene", 500, 560, "glowing kidneys and bladder in coral, dark background, no text"),
  "koerper-sys-fortpflanzung": d(KOERPER, 8, "scene", 500, 560, "an abstract glowing cell division and a tiny embryo motif in rose, dark background, no text"),
  "koerper-sys-lymph": d(KOERPER, 8, "scene", 500, 560, "glowing lymph vessels and lymph nodes in green, dark background, no text"),
  "koerper-sys-haut": d(KOERPER, 8, "scene", 500, 560, "a glowing skin cross-section with layers in warm amber, dark background, no text"),
  "koerper-kette-atome": d(KOERPER, 8, "scene", 500, 500, "a glowing atom with orbiting electrons, dark background, no text"),
  "koerper-kette-molekuele": d(KOERPER, 8, "scene", 500, 500, "a glowing molecule model of connected spheres, dark background, no text"),
  "koerper-kette-zellen": d(KOERPER, 8, "scene", 500, 500, "a glowing human cell with a nucleus in cross-section, dark background, no text"),
  "koerper-kette-gewebe": d(KOERPER, 8, "scene", 500, 500, "glowing tissue cells packed in a pattern, dark background, no text"),
  "koerper-kette-organe": d(KOERPER, 8, "scene", 500, 500, "a glowing human heart, dark background, no text"),
  "koerper-kette-organsysteme": d(KOERPER, 8, "scene", 500, 500, "a glowing network of connected organs, dark background, no text"),
  "koerper-kette-koerper": d(KOERPER, 8, "scene", 500, 500, "a glowing human body silhouette, dark background, no text"),
  "koerper-zelle": d(KOERPER, 8, "scene", 1000, 700, "a large glowing human cell in cross-section with nucleus, mitochondria and membrane, in blue, gold and violet, dark background, no text"),
  "koerper-leben-embryo": d(KOERPER, 8, "scene", 500, 600, "a human embryo in the womb, soft glow, painterly, dark background, no text"),
  "koerper-leben-kindheit": d(KOERPER, 8, "scene", 500, 600, "a happy child in a meadow, soft light, painterly, dark background, no text"),
  "koerper-leben-jugend": d(KOERPER, 8, "scene", 500, 600, "a teenager with a backpack at dusk, soft light, painterly, dark background, no text"),
  "koerper-leben-erwachsen": d(KOERPER, 8, "scene", 500, 600, "an adult standing in a calm landscape, soft light, painterly, dark background, no text"),
  "koerper-leben-alter": d(KOERPER, 8, "scene", 500, 600, "an elderly person looking at the sunset, soft light, painterly, dark background, no text"),
  "koerper-gesund-ernaehrung": d(KOERPER, 8, "scene", 500, 500, "a bowl of colourful fresh vegetables and fruit, dark background, no text"),
  "koerper-gesund-bewegung": d(KOERPER, 8, "scene", 500, 500, "a person jogging at sunrise, dark background, no text"),
  "koerper-gesund-schlaf": d(KOERPER, 8, "scene", 500, 500, "a person sleeping under a night sky, dark background, no text"),
  "koerper-gesund-stress": d(KOERPER, 8, "scene", 500, 500, "a calm hand on a chest with a soft glow, dark background, no text"),
  "koerper-gesund-immun": d(KOERPER, 8, "scene", 500, 500, "an abstract shield of light over a body outline, dark background, no text"),
  "koerper-gesund-darm": d(KOERPER, 8, "scene", 500, 500, "an abstract gut with glowing bacteria, dark background, no text"),
  "koerper-gesund-mental": d(KOERPER, 8, "scene", 500, 500, "a person meditating in a calm room, dark background, no text"),
  "koerper-gesund-langlebigkeit": d(KOERPER, 8, "scene", 500, 500, "a tree with deep roots and an hourglass, dark background, no text"),
  "koerper-forschung-neuro": d(KOERPER, 8, "scene", 500, 420, "a glowing brain scan with neural connections, dark background, no text"),
  "koerper-forschung-genetik": d(KOERPER, 8, "scene", 500, 420, "a glowing DNA double helix, dark background, no text"),
  "koerper-forschung-mikrobiom": d(KOERPER, 8, "scene", 500, 420, "glowing gut bacteria under a microscope, dark background, no text"),
  "koerper-forschung-regeneration": d(KOERPER, 8, "scene", 500, 420, "stem cells in a petri dish, soft glow, dark background, no text"),
  "koerper-forschung-langlebigkeit": d(KOERPER, 8, "scene", 500, 420, "an hourglass with golden light and a cell, dark background, no text"),
  "koerper-link-naehrstoffe": d(KOERPER, 8, "scene", 600, 480, "colourful fruit and vegetables with glowing vitamin molecules, dark background, no text"),
  "koerper-link-pflanzen": d(KOERPER, 8, "scene", 600, 480, "a medicinal plant with glowing leaves, dark background, no text"),
  "koerper-link-mineralien": d(KOERPER, 8, "scene", 600, 480, "raw mineral crystals in blue and white, dark background, no text"),
  "koerper-link-frequenzen": d(KOERPER, 8, "scene", 600, 480, "a glowing sound wave pattern in sand, dark background, no text"),
  "koerper-hirn": d(KOERPER, 8, "scene", 1200, 700, "a glowing human brain in profile with golden neural pathways and tiny sparks, dark background, no text"),
  "koerper-funktion-stoffwechsel": d(KOERPER, 8, "scene", 500, 500, "a glowing flame inside a cell with energy particles, dark background, no text"),
  "koerper-funktion-hormone": d(KOERPER, 8, "scene", 500, 500, "glowing hormone molecules flowing in a blood vessel, dark background, no text"),
  "koerper-funktion-regeneration": d(KOERPER, 8, "scene", 500, 500, "new green skin cells growing over a small wound, soft glow, dark background, no text"),
  "koerper-funktion-wachstum": d(KOERPER, 8, "scene", 500, 500, "a seedling and a growing silhouette of a child, soft glow, dark background, no text"),
  "koerper-funktion-temperatur": d(KOERPER, 8, "scene", 500, 500, "a glowing thermometer over a body outline, dark background, no text"),
  "koerper-funktion-entgiftung": d(KOERPER, 8, "scene", 500, 500, "a glowing liver and kidneys with clean water drops, dark background, no text"),
  "koerper-funktion-sinne": d(KOERPER, 8, "scene", 500, 500, "an eye, an ear and a nose glowing as signals, dark background, no text"),
  "koerper-funktion-homoeostase": d(KOERPER, 8, "scene", 500, 500, "balanced glowing scales over a body outline, dark background, no text"),
  "freq-hero": d(FREQ, 8, "scene", 2800, 1300, "a serene translucent human figure in the centre right with glowing energy lines and seven soft chakra lights, concentric sound waves around it, in a night landscape with a lake, mountains, a starry sky and a distant galaxy, warm sunset glow at the horizon, a dark calm area on the left for text, no text, no letters, no circles with icons"),
  "freq-kugel-worte": d(FREQ, 8, "scene", 600, 600, "a glowing sphere showing a human head profile with a sound wave, cyan, dark background, no text"),
  "freq-kugel-licht": d(FREQ, 8, "scene", 600, 600, "a glowing sphere with a bright sun and rays, orange, dark background, no text"),
  "freq-kugel-nahrung": d(FREQ, 8, "scene", 600, 600, "a glowing sphere with a green plant sprout, green, dark background, no text"),
  "freq-kugel-klaenge": d(FREQ, 8, "scene", 600, 600, "a glowing sphere with a purple sound wave pattern, violet, dark background, no text"),
  "freq-kugel-materialien": d(FREQ, 8, "scene", 600, 600, "a glowing sphere with a faceted violet crystal, purple, dark background, no text"),
  "freq-kugel-umgebung": d(FREQ, 8, "scene", 600, 600, "a glowing sphere with a mountain lake landscape at dusk, blue, dark background, no text"),
  "freq-kraft-radio": d(FREQ, 8, "scene", 700, 420, "a glowing vintage radio with a dial and a blue sound wave, dark background, no text"),
  "freq-kraft-resonanz": d(FREQ, 8, "scene", 700, 420, "a Newton's cradle with golden glowing spheres and light waves, dark background, no text"),
  "freq-kraft-levitation": d(FREQ, 8, "scene", 700, 420, "a stone floating above a glowing field of sound waves, dark background, no text"),
  "freq-kraft-medizin": d(FREQ, 8, "scene", 700, 420, "focused blue and red energy waves meeting at a cell, dark background, no text"),
  "freq-welt-natur": d(FREQ, 8, "scene", 600, 400, "a waterfall in a green valley with mist, dark background, no text"),
  "freq-welt-koerper": d(FREQ, 8, "scene", 600, 400, "a glowing brain and a human head profile with a sound wave, dark background, no text"),
  "freq-welt-materialien": d(FREQ, 8, "scene", 600, 400, "glowing crystals and metal forms, dark background, no text"),
  "freq-welt-technologie": d(FREQ, 8, "scene", 600, 400, "a tall tower with lightning and glowing energy, dark background, no text"),
  "freq-welt-kulturen": d(FREQ, 8, "scene", 600, 400, "Egyptian pyramids and a stone temple at sunset, dark background, no text"),
  "freq-welt-kosmos": d(FREQ, 8, "scene", 600, 400, "a spiral galaxy with planets, dark background, no text"),
  "freq-schluss": d(FREQ, 8, "scene", 2800, 500, "a person sitting in meditation seen from behind on a rock at a lake at sunset, mountains, a dark calm area on the left for text, no text, no letters"),
  "atem-hero": d(ATEM, 8, "scene", 2800, 1300, "a serene man meditating in lotus position at the centre right, translucent glowing body with luminous blue lungs and bronchial tree and a warm orange glow at the diaphragm, a calm mountain lake at dusk behind him with forest on both sides and a golden sunset sky, a dark calm area on the left for text, no text, no letters, no icons"),
  "atem-karte-techniken": d(ATEM, 8, "scene", 800, 500, "a person meditating on a rock at sunset in the mountains, dark cinematic, no text"),
  "atem-karte-nerven": d(ATEM, 8, "scene", 800, 500, "a glowing blue nerve network with sparks and a bright neuron, dark cinematic, no text"),
  "atem-karte-wissen": d(ATEM, 8, "scene", 800, 500, "a glowing human head profile in profile with a luminous brain and lungs, dark cinematic, no text"),
  "atem-karte-tradition": d(ATEM, 8, "scene", 800, 500, "a monk meditating in a snowy mountain landscape, dark cinematic, no text"),
  "atem-koerper": d(ATEM, 8, "scene", 1400, 1600, "translucent human torso with glowing blue lungs, bronchial tree, heart and diaphragm, warm orange glow below, dark background, no text, no letters"),
  "atem-mehr-meditation": d(ATEM, 8, "scene", 800, 500, "a woman meditating at sunrise in a forest, dark cinematic, no text"),
  "atem-mehr-tradition": d(ATEM, 8, "scene", 800, 500, "a man meditating in the snow in the mountains, dark cinematic, no text"),
  "atem-mehr-nerven": d(ATEM, 8, "scene", 800, 500, "glowing nerve cells connected by light, blue and violet, dark cinematic, no text"),
  "atem-mehr-schlaf": d(ATEM, 8, "scene", 800, 500, "a person sleeping peacefully in a dark blue bedroom, dark cinematic, no text"),
  "atem-schluss": d(ATEM, 8, "scene", 2800, 500, "a person sitting in meditation seen from behind on a rock above a misty mountain valley at sunrise, golden light, a dark calm area on the left for text, no text, no letters"),
  "beschwerden-hero": d(BESCH, 8, "scene", 2800, 1300, "a standing translucent human figure with seven softly glowing chakra points along the spine and fine blue energy lines, in a dark mountain landscape with forest on both sides and a golden sunset sky, a dark calm area on the left for text, no text, no letters, no icons, no circles"),
  "beschwerden-kugel-geist": d(BESCH, 8, "scene", 600, 600, "a glowing human head profile with a luminous brain in cyan inside a round frame, dark background, no text"),
  "beschwerden-kugel-atmung": d(BESCH, 8, "scene", 600, 600, "glowing lungs in cyan and blue inside a round frame, dark background, no text"),
  "beschwerden-kugel-ernaehrung": d(BESCH, 8, "scene", 600, 600, "a glowing red apple inside a round frame, dark background, no text"),
  "beschwerden-kugel-pflanzen": d(BESCH, 8, "scene", 600, 600, "a glowing green plant sprout inside a round frame, dark background, no text"),
  "beschwerden-kugel-chakren": d(BESCH, 8, "scene", 600, 600, "a glowing pink lotus flower inside a round frame, dark background, no text"),
  "beschwerden-kugel-frequenzen": d(BESCH, 8, "scene", 600, 600, "a glowing violet sound wave inside a round frame, dark background, no text"),
  "beschwerden-kugel-kristalle": d(BESCH, 8, "scene", 600, 600, "a glowing violet crystal cluster inside a round frame, dark background, no text"),
  "beschwerden-kugel-lebensstil": d(BESCH, 8, "scene", 600, 600, "a glowing orange sun inside a round frame, dark background, no text"),
  "beschwerden-erkaeltung": d(BESCH, 8, "scene", 600, 700, "a young woman with a cold wrapped in a blanket holding a tissue, soft light, no text"),
  "beschwerden-kopf": d(BESCH, 8, "scene", 600, 700, "a woman holding her head, a glowing brain in orange behind her, dark background, no text"),
  "beschwerden-magen": d(BESCH, 8, "scene", 600, 700, "a glowing human stomach and intestines in orange and red, dark background, no text"),
  "beschwerden-schlaf": d(BESCH, 8, "scene", 600, 700, "a person lying awake in bed at night, blue light, no text"),
  "beschwerden-stress": d(BESCH, 8, "scene", 600, 700, "a person meditating at sunset in the mountains, no text"),
  "beschwerden-haut": d(BESCH, 8, "scene", 600, 700, "a close up of skin with a red patch, soft light, no text"),
  "beschwerden-frauen": d(BESCH, 8, "scene", 600, 700, "a pink lotus flower in soft light, dark background, no text"),
  "beschwerden-schmerz": d(BESCH, 8, "scene", 600, 700, "a glowing knee joint with orange pain glow, dark background, no text"),
  "beschwerden-analyse": d(BESCH, 8, "scene", 900, 1100, "a translucent human head and torso in profile with a glowing orange brain and stomach, dark blue background, no text"),
  "beschwerden-empf-pflanzen": d(BESCH, 8, "scene", 600, 420, "fresh mint leaves and herbs, dark cinematic, no text"),
  "beschwerden-empf-ernaehrung": d(BESCH, 8, "scene", 600, 420, "a bowl of fresh vegetables and grains, dark cinematic, no text"),
  "beschwerden-empf-wasser": d(BESCH, 8, "scene", 600, 420, "a glass of clear water with a waterfall behind, dark cinematic, no text"),
  "beschwerden-empf-atem": d(BESCH, 8, "scene", 600, 420, "a person meditating on a rock at sunset, dark cinematic, no text"),
  "beschwerden-empf-meditation": d(BESCH, 8, "scene", 600, 420, "a person meditating in a forest with golden light, dark cinematic, no text"),
  "beschwerden-empf-kristalle": d(BESCH, 8, "scene", 600, 420, "purple amethyst crystals, dark cinematic, no text"),
  "beschwerden-empf-koerperarbeit": d(BESCH, 8, "scene", 600, 420, "a back with acupressure points and hands, dark cinematic, no text"),
  "beschwerden-empf-lebensstil": d(BESCH, 8, "scene", 600, 420, "a sunrise over a mountain landscape, dark cinematic, no text"),
  "chakren-hero": d(CHAKREN, 8, "scene", 2800, 1300, "a serene woman meditating in lotus position at a calm mountain lake at dusk, translucent glowing body with seven softly glowing chakra points along the spine in rainbow colours and a glowing violet lotus above the crown of her head, stars and a purple twilight sky, forest and mountains on both sides, a dark calm area on the left for text, no text, no letters, no icons"),
  "chakren-symbol-wurzel": d(CHAKREN, 8, "black", 800, 800, "red lotus with four petals inside a square, glowing sacred geometry, on a pure black background, no text"),
  "chakren-symbol-sakral": d(CHAKREN, 8, "black", 800, 800, "orange lotus with six petals around a crescent moon, glowing sacred geometry, on a pure black background, no text"),
  "chakren-symbol-solar": d(CHAKREN, 8, "black", 800, 800, "yellow lotus with ten petals around a downward triangle, glowing sacred geometry, on a pure black background, no text"),
  "chakren-symbol-herz": d(CHAKREN, 8, "black", 800, 800, "green lotus with twelve petals around a six-pointed star, glowing sacred geometry, on a pure black background, no text"),
  "chakren-symbol-hals": d(CHAKREN, 8, "black", 800, 800, "light blue lotus with sixteen petals around a white circle, glowing sacred geometry, on a pure black background, no text"),
  "chakren-symbol-stirn": d(CHAKREN, 8, "black", 800, 800, "indigo lotus with two petals and a glowing centre, glowing sacred geometry, on a pure black background, no text"),
  "chakren-symbol-krone": d(CHAKREN, 8, "black", 800, 800, "violet and white lotus with a thousand fine petals, glowing gold centre, glowing sacred geometry, on a pure black background, no text"),
  "chakren-med-erdung": d(CHAKREN, 8, "scene", 400, 400, "a calm meditation scene for the theme erdung, a person sitting in meditation, dark cinematic, no text"),
  "chakren-med-weite": d(CHAKREN, 8, "scene", 400, 400, "a calm meditation scene for the theme weite, a person sitting in meditation, dark cinematic, no text"),
  "chakren-med-licht": d(CHAKREN, 8, "scene", 400, 400, "a calm meditation scene for the theme licht, a person sitting in meditation, dark cinematic, no text"),
  "chakren-med-klang": d(CHAKREN, 8, "scene", 400, 400, "a calm meditation scene for the theme klang, a person sitting in meditation, dark cinematic, no text"),
  "chakren-med-stille": d(CHAKREN, 8, "scene", 400, 400, "a calm meditation scene for the theme stille, a person sitting in meditation, dark cinematic, no text"),
  "chakren-med-reinigung": d(CHAKREN, 8, "scene", 400, 400, "a calm meditation scene for the theme vorstellung, a person sitting in meditation, dark cinematic, no text"),
  "chakren-stein-roter-jaspis": d(CHAKREN, 8, "black", 600, 600, "one Roter Jaspis crystal (Quarz-Varietät, rot durch Eisenoxid), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-karneol": d(CHAKREN, 8, "black", 600, 600, "one Karneol crystal (orange-roter Chalcedon (SiO₂)), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-orangenkalzit": d(CHAKREN, 8, "black", 600, 600, "one Orangenkalzit crystal (orangefarbener Calcit (CaCO₃), weich), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-mondstein": d(CHAKREN, 8, "black", 600, 600, "one Mondstein crystal (Feldspat mit bläulichem Schimmer), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-bernstein": d(CHAKREN, 8, "black", 600, 600, "one Bernstein crystal (fossiles Baumharz, kein Mineral), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-tigerauge": d(CHAKREN, 8, "black", 600, 600, "one Tigerauge crystal (Quarz mit Fasereinschlüssen, goldbraun schimmernd), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-gruener-aventurin": d(CHAKREN, 8, "black", 600, 600, "one Grüner Aventurin crystal (Quarz mit Glimmer-Einschlüssen), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-rhodonit": d(CHAKREN, 8, "black", 600, 600, "one Rhodonit crystal (rosa Mangansilikat), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-smaragd": d(CHAKREN, 8, "black", 600, 600, "one Smaragd crystal (grüne Beryll-Varietät), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-aquamarin": d(CHAKREN, 8, "black", 600, 600, "one Aquamarin crystal (blaue Beryll-Varietät), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-sodalith": d(CHAKREN, 8, "black", 600, 600, "one Sodalith crystal (blaues Natrium-Aluminium-Silikat), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-tuerkis": d(CHAKREN, 8, "black", 600, 600, "one Türkis crystal (Kupfer-Aluminium-Phosphat, himmelblau bis grünlich), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-blauer-chalcedon": d(CHAKREN, 8, "black", 600, 600, "one Blauer Chalcedon crystal (hellblaue Chalcedon-Varietät (SiO₂)), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-selenit": d(CHAKREN, 8, "black", 600, 600, "one Selenit crystal (durchsichtiger Gips (CaSO₄·2H₂O), sehr weich), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-stein-lepidolith": d(CHAKREN, 8, "black", 600, 600, "one Lepidolith crystal (Lithium-Glimmer, rosa bis violett), softly glowing, studio macro, on a pure black background, no text"),
  "chakren-essen-rote-bete": d(CHAKREN, 8, "black", 600, 600, "Rote Bete (Wurzelgemüse, roter Farbstoff Betanin), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-suesskartoffel": d(CHAKREN, 8, "black", 600, 600, "Süßkartoffel (Knolle, Stärke; orange Sorten mit Beta-Carotin), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-orange": d(CHAKREN, 8, "black", 600, 600, "Orange (Zitrusfrucht, Vitamin C), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-mango": d(CHAKREN, 8, "black", 600, 600, "Mango (Steinfrucht, Carotinoide, Vitamin C), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-aprikose": d(CHAKREN, 8, "black", 600, 600, "Aprikose (Steinfrucht, Carotinoide), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-banane": d(CHAKREN, 8, "black", 600, 600, "Banane (Frucht, Kalium, Stärke und Zucker), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-mais": d(CHAKREN, 8, "black", 600, 600, "Mais (Getreide, Stärke, gelber Farbstoff Lutein), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-gruenkohl": d(CHAKREN, 8, "black", 600, 600, "Grünkohl (Kohlgemüse, Vitamin K, Carotinoide), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-kiwi": d(CHAKREN, 8, "black", 600, 600, "Kiwi (Frucht, Vitamin C), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-pflaume": d(CHAKREN, 8, "black", 600, 600, "Pflaume (Steinfrucht, Anthocyane in der Schale), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-brombeeren": d(CHAKREN, 8, "black", 600, 600, "Brombeeren (Beere, Anthocyane), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-kraeutertee": d(CHAKREN, 8, "black", 600, 600, "Kräutertee (Aufguss aus Kräutern, z. B. Kamille oder Pfefferminze), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-birne": d(CHAKREN, 8, "black", 600, 600, "Birne (Kernobst, Ballaststoffe), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-trauben": d(CHAKREN, 8, "black", 600, 600, "Trauben (Beere; blaue Sorten mit Anthocyanen in der Schale), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-aubergine": d(CHAKREN, 8, "black", 600, 600, "Aubergine (Fruchtgemüse, Anthocyane in der Schale), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-rotkohl": d(CHAKREN, 8, "black", 600, 600, "Rotkohl (Kohlgemüse, Anthocyane (rot bis blau je nach Säure)), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-kokosnuss": d(CHAKREN, 8, "black", 600, 600, "Kokosnuss (Steinfrucht, Fett (überwiegend gesättigt), Ballaststoffe), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-ananas": d(CHAKREN, 8, "black", 600, 600, "Ananas (Frucht, Enzym Bromelain, Vitamin C), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-essen-lila-gemuese": d(CHAKREN, 8, "black", 600, 600, "Lila Gemüse (z. B. Rotkohl, Aubergine, violette Karotten; Anthocyane), fresh, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-zeder": d(CHAKREN, 8, "black", 600, 600, "Zeder as an aromatic ingredient (holziger Duft des Zedernholzes), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-patchouli": d(CHAKREN, 8, "black", 600, 600, "Patchouli as an aromatic ingredient (Blätter von Pogostemon cablin, erdiger Duft), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-vetiver": d(CHAKREN, 8, "black", 600, 600, "Vetiver as an aromatic ingredient (Wurzel eines Grases, erdig-rauchiger Duft), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-myrrhe": d(CHAKREN, 8, "black", 600, 600, "Myrrhe as an aromatic ingredient (Harz von Commiphora-Arten, balsamisch-herb), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-suessorange": d(CHAKREN, 8, "black", 600, 600, "Süßorange as an aromatic ingredient (Schalenöl, frisch-fruchtig), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-ylang-ylang": d(CHAKREN, 8, "black", 600, 600, "Ylang-Ylang as an aromatic ingredient (Blüten von Cananga odorata, süß-blumig), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-sandelholz": d(CHAKREN, 8, "black", 600, 600, "Sandelholz as an aromatic ingredient (warm-holziger Duft; Santalum album gilt als gefährdet), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-jasmin": d(CHAKREN, 8, "black", 600, 600, "Jasmin as an aromatic ingredient (Blüten, süß-blumig (meist als Absolue)), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-bergamotte": d(CHAKREN, 8, "black", 600, 600, "Bergamotte as an aromatic ingredient (Schalenöl, zitrusartig-blumig), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-rose": d(CHAKREN, 8, "black", 600, 600, "Rose as an aromatic ingredient (Blüten von Rosa damascena, süß-blumig), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-geranie": d(CHAKREN, 8, "black", 600, 600, "Geranie as an aromatic ingredient (Blätter von Pelargonium, rosig-grüner Duft), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-melisse": d(CHAKREN, 8, "black", 600, 600, "Melisse as an aromatic ingredient (Blätter, zitronig), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-eukalyptus": d(CHAKREN, 8, "black", 600, 600, "Eukalyptus as an aromatic ingredient (Blätter, Cineol, frisch-kampferartig), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-wacholder": d(CHAKREN, 8, "black", 600, 600, "Wacholder as an aromatic ingredient (Beerenzapfen, harzig-frisch), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-weihrauch": d(CHAKREN, 8, "black", 600, 600, "Weihrauch as an aromatic ingredient (Harz von Boswellia-Arten, balsamisch-würzig; wird verräuchert), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-duft-lotus": d(CHAKREN, 8, "black", 600, 600, "Lotus as an aromatic ingredient (zarter Blütenduft; im Handel häufig nachgebildet), with a small glass bottle, glowing in soft light, on a pure black background, no text"),
  "chakren-yoga-berghaltung": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Berghaltung (Tadasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-baum": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Baum (Vrksasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-krieger-i": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Krieger I (Virabhadrasana I) at sunset, dark cinematic, no text"),
  "chakren-yoga-girlande": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Girlande (Malasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-schmetterling": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Schmetterling (Baddha Konasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-taube": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Taube (Eka Pada Rajakapotasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-goettin": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Göttin (Utkata Konasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-boot": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Boot (Navasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-drehsitz": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Drehsitz (Ardha Matsyendrasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-sonnengruss": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Sonnengruß (Surya Namaskar) at sunset, dark cinematic, no text"),
  "chakren-yoga-kobra": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Kobra (Bhujangasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-bruecke": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Brücke (Setu Bandhasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-kamel": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Kamel (Ustrasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-fisch": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Fisch (Matsyasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-schulterstand": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Schulterstand (Sarvangasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-pflug": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Pflug (Halasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-loewenatem": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Löwenatem (Simhasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-kindhaltung": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Kindhaltung (Balasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-sitzende-vorbeuge": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Sitzende Vorbeuge (Paschimottanasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-delfin": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Delfin (Ardha Pincha Mayurasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-wechselatmung": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Wechselatmung (Nadi Shodhana) at sunset, dark cinematic, no text"),
  "chakren-yoga-kopfstand": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Kopfstand (Sirsasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-lotussitz": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Lotussitz (Padmasana) at sunset, dark cinematic, no text"),
  "chakren-yoga-meditation-im-sitzen": d(CHAKREN, 8, "scene", 600, 600, "a person in the yoga pose Meditation im Sitzen (Sukhasana) at sunset, dark cinematic, no text"),
  "chakren-natur-wald": d(CHAKREN, 8, "scene", 800, 500, "Wald: Bäume, Humus, Schatten und Stille, dark cinematic landscape, no text"),
  "chakren-natur-felsen": d(CHAKREN, 8, "scene", 800, 500, "Felsen: Stein und Erde unter den Füßen, dark cinematic landscape, no text"),
  "chakren-natur-garten": d(CHAKREN, 8, "scene", 800, 500, "Garten: Beete und Erde, dark cinematic landscape, no text"),
  "chakren-natur-seen-meer": d(CHAKREN, 8, "scene", 800, 500, "Seen & Meer: Weite Wasserflächen, dark cinematic landscape, no text"),
  "chakren-natur-wasserfaelle": d(CHAKREN, 8, "scene", 800, 500, "Wasserfälle: Rauschendes Wasser, dark cinematic landscape, no text"),
  "chakren-natur-flussufer": d(CHAKREN, 8, "scene", 800, 500, "Flussufer: Fließendes Wasser, dark cinematic landscape, no text"),
  "chakren-natur-sonnenaufgang": d(CHAKREN, 8, "scene", 800, 500, "Sonnenaufgang: Morgenlicht im Freien, dark cinematic landscape, no text"),
  "chakren-natur-wiesen": d(CHAKREN, 8, "scene", 800, 500, "Wiesen: Offene Flächen im Sonnenlicht, dark cinematic landscape, no text"),
  "chakren-natur-weite": d(CHAKREN, 8, "scene", 800, 500, "Weite: Offene Landschaften mit weitem Blick, dark cinematic landscape, no text"),
  "chakren-natur-blumenwiesen": d(CHAKREN, 8, "scene", 800, 500, "Blumenwiesen: Blühende Wiesen, dark cinematic landscape, no text"),
  "chakren-natur-himmel": d(CHAKREN, 8, "scene", 800, 500, "Himmel: Wolken und freie Sicht nach oben, dark cinematic landscape, no text"),
  "chakren-natur-berggipfel": d(CHAKREN, 8, "scene", 800, 500, "Berggipfel: Klare Luft und Fernsicht, dark cinematic landscape, no text"),
  "chakren-natur-nachthimmel": d(CHAKREN, 8, "scene", 800, 500, "Nachthimmel: Sterne fernab von Stadtlicht, dark cinematic landscape, no text"),
  "chakren-natur-daemmerung": d(CHAKREN, 8, "scene", 800, 500, "Dämmerung: Übergang zwischen Tag und Nacht, dark cinematic landscape, no text"),
  "chakren-natur-berge": d(CHAKREN, 8, "scene", 800, 500, "Berge: Weite und klare Luft, dark cinematic landscape, no text"),
  "chakren-natur-sternenhimmel": d(CHAKREN, 8, "scene", 800, 500, "Sternenhimmel: Blick in den Nachthimmel, dark cinematic landscape, no text"),
  "chakren-natur-stille-orte": d(CHAKREN, 8, "scene", 800, 500, "Stille Orte: Plätze ohne Lärm, dark cinematic landscape, no text"),
  // ---- Nährstoff-Seite (Referenzbild 30, Priorität 8)
  "naehrstoffe-hero": d(NAEHR, 8, "scene", 2800, 1300, "a translucent glowing human body in lotus position meditating in a night landscape with mountains, a lake and a starry sky, visible glowing organs (brain, lungs, heart, stomach, intestines) and a network of fine blue and red vessels, a calm dark area on the left for text, no text, no letters, no icons"),
  "naehrstoffe-koerper": d(NAEHR, 8, "black", 2400, 3600, "translucent glowing human body, front view, upper body to knees, brain, lungs, heart, liver, stomach and intestines softly glowing in pink, red and orange, a fine network of blue nerves and vessels, on a pure black background"),
  "naehrstoffe-kat-vitamin": d(NAEHR, 8, "scene", 600, 400, "halved oranges, lemons and fresh citrus fruit with leaves, dark cinematic food photography, no text"),
  "naehrstoffe-kat-mineral": d(NAEHR, 8, "scene", 600, 400, "blue and white raw mineral crystals, dark cinematic food photography, no text"),
  "naehrstoffe-kat-amino": d(NAEHR, 8, "scene", 600, 400, "eggs, nuts, beans and seeds in small bowls, dark cinematic food photography, no text"),
  "naehrstoffe-kat-fett": d(NAEHR, 8, "scene", 600, 400, "fresh salmon fillet with herbs, dark cinematic food photography, no text"),
  "naehrstoffe-kat-spur": d(NAEHR, 8, "scene", 600, 400, "green leaves and sprouts on dark soil, dark cinematic food photography, no text"),
  "naehrstoffe-kat-enzym": d(NAEHR, 8, "scene", 600, 400, "halved papaya and pineapple, dark cinematic food photography, no text"),
  "naehrstoffe-kat-pflanzenstoff": d(NAEHR, 8, "scene", 600, 400, "blueberries, red grapes, purple cabbage and colourful berries, dark cinematic food photography, no text"),
  "naehrstoffe-info-wirken": d(NAEHR, 8, "scene", 800, 450, "a glowing cell membrane with molecules, vitamins and co-factors docking, scientific illustration, blue and purple light, no text"),
  "naehrstoffe-info-quellen": d(NAEHR, 8, "scene", 800, 450, "salmon, broccoli, blueberries, nuts and leafy greens arranged together, no text"),
  "naehrstoffe-info-einnahme": d(NAEHR, 8, "scene", 800, 450, "capsules, a glass of water and fresh lemon on a table in warm light, no text"),
  "naehrstoffe-info-mangel": d(NAEHR, 8, "scene", 800, 450, "a tired person sitting with glowing red points on the body, dark cinematic, no text"),
  "naehrstoff-vit-d": d(NAEHR, 8, "scene", 600, 500, "vitamin D: a sunny morning with eggs, salmon and mushrooms, dark cinematic food photography, no text"),
  "naehrstoff-vit-b12": d(NAEHR, 8, "scene", 600, 500, "vitamin B12: fresh meat, fish and eggs, dark cinematic food photography, no text"),
  "naehrstoff-magnesium": d(NAEHR, 8, "scene", 600, 500, "magnesium: blueberries, dark leafy greens, nuts and seeds, dark cinematic food photography, no text"),
  "naehrstoff-zink": d(NAEHR, 8, "scene", 600, 500, "zinc: raw stones and pumpkin seeds, cashews and cheese, dark cinematic food photography, no text"),
  "naehrstoff-omega3": d(NAEHR, 8, "scene", 600, 500, "omega-3: fresh salmon fillets, walnuts and linseed oil, dark cinematic food photography, no text"),
  "naehrstoff-eisen": d(NAEHR, 8, "scene", 600, 500, "iron: lentils, red meat and spinach, deep red tones, dark cinematic food photography, no text"),
  "naehrstoff-vit-c": d(NAEHR, 8, "scene", 600, 500, "vitamin C: halved oranges, lemons, red peppers and berries, dark cinematic food photography, no text"),
  "naehrstoff-calcium": d(NAEHR, 8, "scene", 600, 500, "calcium: white chalk-like minerals, milk, cheese and almonds, dark cinematic food photography, no text"),
  "naehrstoff-vit-b": d(NAEHR, 8, "scene", 600, 500, "B vitamins: whole grains, legumes, eggs and leafy greens, dark cinematic food photography, no text"),
  "naehrstoff-vit-a": d(NAEHR, 8, "scene", 600, 500, "vitamin A: carrots, sweet potatoes and liver, dark cinematic food photography, no text"),
  "naehrstoff-vit-e": d(NAEHR, 8, "scene", 600, 500, "vitamin E: sunflower seeds, almonds and a glass of plant oil, dark cinematic food photography, no text"),
  "naehrstoff-vit-k": d(NAEHR, 8, "scene", 600, 500, "vitamin K: kale, broccoli and spinach, dark cinematic food photography, no text"),
  "naehrstoff-kalium": d(NAEHR, 8, "scene", 600, 500, "potassium: bananas, potatoes, beans and dried apricots, dark cinematic food photography, no text"),
  "naehrstoff-jod": d(NAEHR, 8, "scene", 600, 500, "iodine: sea fish, seaweed and a small bowl of salt, dark cinematic food photography, no text"),
  "naehrstoff-selen": d(NAEHR, 8, "scene", 600, 500, "selenium: brazil nuts, fish and eggs, dark cinematic food photography, no text"),
  "naehrstoff-protein": d(NAEHR, 8, "scene", 600, 500, "protein: eggs, beans, lentils, fish and cheese, dark cinematic food photography, no text"),
  "naehrstoff-amino": d(NAEHR, 8, "scene", 600, 500, "amino acids: abstract glowing molecular chains with eggs and legumes, dark cinematic food photography, no text"),
  "naehrstoff-omega6": d(NAEHR, 8, "scene", 600, 500, "omega-6: sunflower seeds, safflower oil and nuts, dark cinematic food photography, no text"),
  "naehrstoff-omega9": d(NAEHR, 8, "scene", 600, 500, "omega-9: olives, olive oil and avocado, dark cinematic food photography, no text"),
  "naehrstoff-q10": d(NAEHR, 8, "scene", 600, 500, "coenzyme Q10: a glowing mitochondrion beside fish and nuts, dark cinematic food photography, no text"),
  "naehrstoff-enzyme": d(NAEHR, 8, "scene", 600, 500, "digestive enzymes: fresh pineapple and papaya halves, dark cinematic food photography, no text"),
  "naehrstoff-polyphenole": d(NAEHR, 8, "scene", 600, 500, "polyphenols: berries, red cabbage, green tea and dark cocoa, dark cinematic food photography, no text"),
  "naehrstoff-carotinoide": d(NAEHR, 8, "scene", 600, 500, "carotenoids: tomatoes, carrots, pumpkin and peppers in orange and red, dark cinematic food photography, no text"),
  "naehrstoff-glucosinolate": d(NAEHR, 8, "scene", 600, 500, "glucosinolates: broccoli, cabbage, radish and rocket, dark cinematic food photography, no text"),
  "naehrstoff-cholin": d(NAEHR, 8, "scene", 600, 500, "choline: eggs, soybeans and wheat germ, dark cinematic food photography, no text"),
  "naehrstoff-ballaststoffe": d(NAEHR, 8, "scene", 600, 500, "dietary fibre: whole grain bread, oats, legumes and seeds, dark cinematic food photography, no text"),
  "naehrstoff-probiotika": d(NAEHR, 8, "scene", 600, 500, "probiotics: yoghurt, kefir and sauerkraut in glass jars, dark cinematic food photography, no text"),
} as const satisfies Record<string, SlotDef>;

export type SlotName = keyof typeof SLOTS;

/** Pictures for atlas entries are generated per entry: `atlas-<id>`, motif on black, square. */
export const ATLAS_SLOT: SlotDef = { w: 1000, h: 1000, bg: "black", prio: 3, page: "Atlas", prompt: "one botanical or mineral subject, scientific illustration meets glowing light, on a pure black background" };

export function slotDef(name: string): SlotDef | undefined {
  return (SLOTS as Record<string, SlotDef>)[name] ?? (name.startsWith("atlas-") ? ATLAS_SLOT : undefined);
}
